<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>cf773a9d-ec7d-452a-898e-af04d1bff2f2</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="StackExchange.Redis" Version="2.8.31" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Aegis.Application\Aegis.Application.csproj" />
    <ProjectReference Include="..\Aegis.Infrastructure\Aegis.Infrastructure.csproj" />
  </ItemGroup>

</Project>
